name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: set crlf
        shell: bash
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v3

      - name: Compile
        shell: bash
        run: g++ turbo.cpp -o turbo.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          path: turbo.exe
      - name: Try With Bash
        shell: bash
        run: ./turbo.exe hi yes -- 124
      - name: Try without Bash
        run: ./turbo.exe hi yes -- 124
